# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _needle

import flatbuffers

class Code(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCode(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Code()
        x.Init(buf, n + offset)
        return x

    # Code
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Code
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Code
    def Method(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Sequences import Sequences
            obj = Sequences()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Code
    def MethodLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def CodeStart(builder): builder.StartObject(2)
def CodeAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def CodeAddMethod(builder, method): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(method), 0)
def CodeStartMethodVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CodeEnd(builder): return builder.EndObject()
