# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: needle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='needle.proto',
  package='needle',
  syntax='proto3',
  serialized_pb=_b('\n\x0cneedle.proto\x12\x06needle\"\x92\x01\n\tSequences\x12$\n\x04kind\x18\x01 \x01(\x0e\x32\x16.needle.Sequences.Kind\x12\n\n\x02id\x18\x02 \x01(\x05\x12\"\n\x03seq\x18\x03 \x03(\x0b\x32\x15.needle.Sequences.Seq\x1a\x12\n\x03Seq\x12\x0b\n\x03vec\x18\x01 \x03(\x02\"\x1b\n\x04Kind\x12\x07\n\x03\x42UG\x10\x00\x12\n\n\x06METHOD\x10\x01\"5\n\x04\x43ode\x12\n\n\x02id\x18\x01 \x01(\x05\x12!\n\x06method\x18\x02 \x03(\x0b\x32\x11.needle.Sequencesb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SEQUENCES_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='needle.Sequences.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METHOD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=144,
  serialized_end=171,
)
_sym_db.RegisterEnumDescriptor(_SEQUENCES_KIND)


_SEQUENCES_SEQ = _descriptor.Descriptor(
  name='Seq',
  full_name='needle.Sequences.Seq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='needle.Sequences.Seq.vec', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=142,
)

_SEQUENCES = _descriptor.Descriptor(
  name='Sequences',
  full_name='needle.Sequences',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='needle.Sequences.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='needle.Sequences.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='needle.Sequences.seq', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SEQUENCES_SEQ, ],
  enum_types=[
    _SEQUENCES_KIND,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=171,
)


_CODE = _descriptor.Descriptor(
  name='Code',
  full_name='needle.Code',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='needle.Code.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='needle.Code.method', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=226,
)

_SEQUENCES_SEQ.containing_type = _SEQUENCES
_SEQUENCES.fields_by_name['kind'].enum_type = _SEQUENCES_KIND
_SEQUENCES.fields_by_name['seq'].message_type = _SEQUENCES_SEQ
_SEQUENCES_KIND.containing_type = _SEQUENCES
_CODE.fields_by_name['method'].message_type = _SEQUENCES
DESCRIPTOR.message_types_by_name['Sequences'] = _SEQUENCES
DESCRIPTOR.message_types_by_name['Code'] = _CODE

Sequences = _reflection.GeneratedProtocolMessageType('Sequences', (_message.Message,), dict(

  Seq = _reflection.GeneratedProtocolMessageType('Seq', (_message.Message,), dict(
    DESCRIPTOR = _SEQUENCES_SEQ,
    __module__ = 'needle_pb2'
    # @@protoc_insertion_point(class_scope:needle.Sequences.Seq)
    ))
  ,
  DESCRIPTOR = _SEQUENCES,
  __module__ = 'needle_pb2'
  # @@protoc_insertion_point(class_scope:needle.Sequences)
  ))
_sym_db.RegisterMessage(Sequences)
_sym_db.RegisterMessage(Sequences.Seq)

Code = _reflection.GeneratedProtocolMessageType('Code', (_message.Message,), dict(
  DESCRIPTOR = _CODE,
  __module__ = 'needle_pb2'
  # @@protoc_insertion_point(class_scope:needle.Code)
  ))
_sym_db.RegisterMessage(Code)


# @@protoc_insertion_point(module_scope)
