# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _Sequences

import flatbuffers

class Seq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSeq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Seq()
        x.Init(buf, n + offset)
        return x

    # Seq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Seq
    def Vec(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Seq
    def VecLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SeqStart(builder): builder.StartObject(1)
def SeqAddVec(builder, vec): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vec), 0)
def SeqStartVecVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SeqEnd(builder): return builder.EndObject()
